### ISSUE TITLE
All chat shows as if you typed it

### ISSUE THREAD

**Issue by IasonKalaitzakis** [RefracDevelopment/SimpleStaffChat#34]
Latest 4.3.0 version makes chat appear as if you typed everything, even if it is from other users.

![image](https://github.com/RefracDevelopment/SimpleStaffChat/assets/31860283/4dfe6d00-a9d1-4873-8e35-07842172608f)
This is three different people typing, but it shows up as if I typed everything^

Using the FreedomChat plugin that makes chat not reportable, not sure if that has any affect on it.

**Comment by Refrac** [comment]
I'll look into this later. I have an idea of what might be causing it probably the placeholder is being replaced wrong

**Comment by Refrac** [comment]
@IasonKalaitzakis You can get a beta build here: https://github.com/RefracDevelopment/SimpleStaffChat/releases/tag/4.3.1-SNAPSHOT

**Comment by Refrac** [comment]
I've decided to just release this as is.

**Comment by IasonKalaitzakis** [comment]
Does not seem to be fixed in the 4.3.1 I downloaded from Spigot :/

**Comment by Refrac** [comment]
@IasonKalaitzakis Alright i'll try some more stuff this really isn't an easy issue to fix since i have no way of testing this myself as i don't have any alts

**Comment by IasonKalaitzakis** [comment]
After some testing myself, it seems that your own place holders like %player% work fine, but as soon as I use other plugin's placeholders like %luckperms_prefix%%essentials_nickname% that I've been using, it uses my own instead of the senders. Hope that helps.

**Comment by Refrac** [comment]
hmm okay thanks yeah that should help

**Comment by Refrac** [comment]
@IasonKalaitzakis Here is a beta build for testing https://github.com/RefracDevelopment/SimpleStaffChat/releases/tag/Spigot-4.3.2

**Comment by IasonKalaitzakis** [comment]
Same issue with 4.3.2, the plugin's own placeholders work alright but other plugins' placeholders use the current player's info instead of the senders info.

**Comment by Refrac** [comment]
@IasonKalaitzakis ah okay so it's PlaceholderAPI placeholders being replaced wrong hmm

**Comment by Refrac** [comment]
I'll release another beta soonish

**Comment by Refrac** [comment]
@IasonKalaitzakis Here is another beta build i've changed the way PlaceholderAPI placeholders are replaced: https://github.com/RefracDevelopment/SimpleStaffChat/releases/tag/Spigot-4.3.2-beta

**Comment by Refrac** [comment]
@IasonKalaitzakis ^ Just checking have you tried this yet?

**Comment by IasonKalaitzakis** [comment]
> @IasonKalaitzakis ^ Just checking have you tried this yet?

Ah sorry hadn't had a chance, will let you know as soon as I do :)

**Comment by IasonKalaitzakis** [comment]
> @IasonKalaitzakis ^ Just checking have you tried this yet?

Just tried it, all PAPI placeholders work fine as well. Ty for fixing :)
